Update Dockerfile to build an image
civitaspo/redash-query-replace pull request #4
Opened 2020-01-28 08:33 UTC by k-hashimoto

Update Dockerfile to install on local environment.

`civitaspo/redash-qr` dose not exist on dockerhub. So I need to build a docker image. 

- Run an [instruction on README](https://github.com/civitaspo/redash-query-replace#development) on Dockerfile.
- Remove "does something useful" from spec/redash/query/replace_spec.rb.

2020-01-29 05:43 UTC, civitaspo commented on Dockerfile
> +ENV REDASH_API_KEY $REDASH_API_KEY
These variables must not be defined. If this image are pushed to a public docker registry, any people can get the api key and url from this image.

2020-01-29 06:15 UTC, civitaspo commented on Dockerfile
>  FROM ruby:2.5-alpine
I am sorry to upload the Dockerfile that doesn't work. Could you rewrite like the below?

```
FROM ruby:2.5 as builder

WORKDIR /tmp/redash-query-replace
COPY . /tmp/redash-query-replace
RUN gem build redash-query-replace.gemspec

FROM ruby:2.5

WORKDIR /work
COPY --from=builder /tmp/redash-query-replace/redash-query-replace-0.0.1.gem .
RUN gem install redash-query-replace-0.0.1.gem

ENTRYPOINT ["redash-qr"]
```

2020-01-29 06:15 UTC, civitaspo requested changes
Please write the commit messages in English.

2020-03-29 01:03 UTC, k-hashimoto commented
I'm sorry for quite slow replay. Dockerfile was updated to remove `ARG` and 'ENV'.  `--env-file` option should be used.  @civitaspo

2020-03-30 22:14 UTC, civitaspo commented on README.md
> +docker build -t ${USER}/redash-rp --build-arg REDASH_URL=<your redash url> --build-arg REDASH_API_KEY=<your redash api key>
Please change this instruction.

2020-03-30 22:14 UTC, civitaspo commented on README.md
> +docker run --rm -v `pwd`/:/vol ${USER}/redash-rp query --from 'database.table1' --to 'database.table2' --id 5
ditto

2020-03-30 22:15 UTC, civitaspo requested changes
Modify a bit.

2020-03-30 23:06 UTC, k-hashimoto commented
Maybe we doesn't need `Use Docker` section. Because I removed `ARG` and `ENV` from Dockerfile.

2020-03-31 23:08 UTC, civitaspo approved these changes

2020-03-31 23:09 UTC, merged

2020-03-31 23:09 UTC, civitaspo commented
thx